site_name: Domino Documentation
theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
extra:
  version:
    provider: mike
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
nav:
  - Getting Started:
      - Introduction: index.md
      - Core Concept: core-concept.md
      - Installation & Setup: setup.md
  - Architecture: architecture.md
